import type Skill from "./datatypes/Skill";

export let tools:Skill[] = [
    {
        name:"Unity",
        icon:"",
        fluency:4
    },
    {
        name:"Visual Studio",
        icon:"",
        fluency:4
    },
    {
        name:"Eclipse",
        icon:"",
        fluency:4
    },
    {
        name:"Godot",
        icon:"",
        fluency:2
    },
    {
        name:"Blender",
        icon:"",
        fluency:0
    },
]

export let programmingLanguages:Skill[] = [
    {
        name:"C#",
        icon:"",
        fluency:4
    },
    {
        name:"Java",
        icon:"",
        fluency:4
    },
    {
        name:"Javascript",
        icon:"",
        fluency:4
    },
    {
        name:"HTML 5",
        icon:"",
        fluency:4
    },
    {
        name:"Typescript",
        icon:"",
        fluency:3
    },
    {
        name:"Python",
        icon:"src/lib/images/python-logo-only.svg",
        fluency:2
    },
    {
        name:"Julia",
        icon:"src/lib/images/python-logo-only.svg",
        fluency:2
    },
    {
        name:"Ruby",
        icon:"",
        fluency:1
    },
    {
        name:"GDScript",
        icon:"",
        fluency:1
    },
    {
        name:"C++",
        icon:"",
        fluency:0
    },
    {
        name:"SQL",
        icon:"",
        fluency:1
    },
    {
        name:"C",
        icon:"",
        fluency:0
    }
]